### ISSUE TITLE
imagine/matisse

### ISSUE THREAD

**Issue by saran110313** [Imaginea/matisse#200]
first error is has not create server
2nd error app.get('/', routes.index);
        ^
TypeError: Cannot call method 'get' of undefined

**Comment by saran110313** [comment]
TypeError: string is not a function
    at Function.exports.lookup (C:\Users\saran\workspace\matissemaster\node_modules\express\lib\view.js:99:21)
    at Function.exports.compile (C:\Users\saran\workspace\matissemaster\node_modules\express\lib\view.js:53:18)
    at ServerResponse.res._render (C:\Users\saran\workspace\matissemaster\node_modules\express\lib\view.js:416:18)
    at ServerResponse.res.render (C:\Users\saran\workspace\matissemaster\node_modules\express\lib\view.js:317:17)
    at renderLogin (C:\Users\saran\workspace\matissemaster\routes\index.js:7:9)
    at EventEmitter.server.render.session_data (C:\Users\saran\workspace\matissemaster\routes\index.js:114:9)
    at EventEmitter.emit (events.js:88:17)
    at EventEmitter.server.render (C:\Users\saran\workspace\matissemaster\routes\index.js:126:20)
    at exports.index (C:\Users\saran\workspace\matissemaster\routes\index.js:135:34)
    at callbacks (C:\Users\saran\workspace\matissemaster\node_modules\express\lib\router\index.js:272:11)

**Comment by saran110313** [comment]
how to solve this problem
