### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by saran110313** [Imaginea/matisse#201]
express 
500 TypeError: Cannot read property 'fn' of undefined

     at ServerResponse.res._render (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/node_modules/express/lib/view.js:428:17)
    at ServerResponse.res.render (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/node_modules/express/lib/view.js:321:17)
    at renderLogin (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/routes/index.js:7:9)
    at EventEmitter. (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/routes/index.js:114:9)
    at EventEmitter.emit (events.js:95:17)
    at EventEmitter.server.render (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/routes/index.js:126:20)
    at exports.index (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/routes/index.js:135:34)
    at callbacks (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/node_modules/express/lib/router/index.js:272:11)
    at param (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/node_modules/express/lib/router/index.js:246:11)
    at pass (/home/local/IGSTDEV/saravanan_k/newworkspace/latest-matisse/node_modules/express/lib/router/index.js:253:5)

**Comment by saran110313** [comment]
how to solve path function is remove the object and add the object function is the clear the agent side.but client side path function only remove the object,and is not a add function.

**Comment by saran110313** [comment]
features.js compatibility browser support
